### ISSUE TITLE
ld: library not found for -lAnalytics

### ISSUE THREAD

**Issue by jaybuangan** [buildreactnative/assemblies#2]
thanks for doing this.  

just followed your instructors and ran this when compiling for the first time.  

Also inside your appdelegate.m, it's looking for API_KEY but your instructions say SEGMENT_API_KEY.

**Comment by tgoldenberg** [comment]
Hi @jaybuangan 

that sounds confusing. The `Keys.plist` file that I have locally (with the Segment api key) has a field of `SEGMENT_API_KEY` with a value set to the api key. So if you replicate that locally it should work fine. The `@"API_KEY"` in appdelegate.m is just a placeholder. 

I'm still trying to find the easiest way to keep the project moving but keeping the Api keys private. Let me look into this and see. Also curious if others face this issue, and if not, why.

It may also be that you need to install the Pods associated with the project. However, when I tested locally on my machine with `git clone`, I found that I didn't need to do so. Anyhow, I will take a look at it

**Comment by jaybuangan** [comment]
Thanks!  I'll delete my folder and do it again.

**Comment by jaybuangan** [comment]
Ok this was my fault.  When i opened it in finder i thought i was looking at the /ios/ folder when opening the .xcworkspace file but i was still in the root folder. Built it again and this time success!  sorry for that.
