### ISSUE TITLE
Request to run locally - dpd file

### ISSUE THREAD

**Issue by sesteva** [buildreactnative/assemblies#9]

**Comment by tgoldenberg** [comment]
@sesteva  good request. I'll see if I can move the API to this Github account and open it up

**Comment by tgoldenberg** [comment]
@sesteva The DPD program is now up at https://github.com/buildreactnative/assemblies_api

I haven't had time to make documentation on running it locally, although it should be as simple as typing `dpd` at the terminal. 

If you wouldn't mind, once you get it running, it would be great to get some documentation here and on the api repo on how to run it locally. Also open to suggestions on modifying the schema, security, etc.
